title: Arjun Kulshreshtha
description: Sr. Manager · B2B Operations & Strategy · AI Infrastructure
url: "https://arjkul.github.io"
baseurl: ""

author:
  name: Arjun Kulshreshtha
  linkedin: https://www.linkedin.com/in/arjunkulshreshtha
  github: https://github.com/arjkul

markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-seo-tag
